Account=CityUser
Password=p4ssw0rd
StubsClasspath=/root/smartcity-compss/stubs
DataClayClientConfig=/root/smartcity-compss/cfgfiles/client.properties
DataClayGlobalConfig=/root/smartcity-compss/cfgfiles/global.properties
DataSets=City
DataSetForStore=City
