ARG ROOT_CONTAINER=registry.gitlab.bsc.es/ppc/software/compss/compss_nvidia:3.3-arm
FROM $ROOT_CONTAINER as builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git build-essential rsync libssl-dev libeigen3-dev libglew-dev libglfw3-dev freeglut3-dev libfreetype6-dev libyaml-cpp-dev libpcap-dev libmatio-dev
RUN apt install -y apt-utils wget && apt install -y --reinstall ca-certificates && wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1.tar.gz && \
    tar xf cmake-3.22.1.tar.gz && \ 
    cd cmake-3.22.1 && \
    ./bootstrap && make -j4 && make install
RUN cmake --version
# RUN apt-get install -y python3-matplotlib python-dev libgdal-dev libcereal-dev python-numpy
# RUN apt-get install -y libgles2-mesa-dev xorg-dev libglu1-mesa-dev
RUN mkdir -p /root/repos
WORKDIR /root/repos

# install development packages (from dustynv jetson-inference repository)
#
RUN apt-get update -y && apt-get install -y --no-install-recommends lsb-release
RUN add-apt-repository --remove "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" && \
    apt-get update && \
    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
    apt-get install -y --no-install-recommends \
          mesa-utils \
          lsb-release \
          gstreamer1.0-tools \
          gstreamer1.0-libav \
          gstreamer1.0-rtsp \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          libgstreamer-plugins-bad1.0-dev && \
    if [ `lsb_release --codename --short` != 'bionic' ]; then \
    apt-get install -y --no-install-recommends \
          gstreamer1.0-plugins-rtp; \
    else echo "skipping packages unavailable for Ubuntu 18.04"; fi \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
# make a copy of this cause it gets purged...
RUN mkdir -p /usr/local/include/gstreamer-1.0/gst && \
    cp -r /usr/include/gstreamer-1.0/gst/webrtc /usr/local/include/gstreamer-1.0/gst && \
    ls -ll /usr/local/include/ && \
    ls -ll /usr/local/include/gstreamer-1.0/gst/webrtc
RUN apt-get update -y && apt install -y build-essential \
    unzip \
    pkg-config \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libgtk-3-dev \
    libatlas-base-dev \
    gfortran \
    python3-dev \
    python3-venv \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libdc1394-22-dev \
    libavresample-dev \
    ffmpeg \
    libjpeg8-dev \
    libjpeg-turbo8-dev \
    liblapack-dev \
    liblapacke-dev \
    libopenblas-dev \
    libpostproc-dev \
    libtbb-dev \
    libtbb2 \
    libtesseract-dev \
    qv4l2 \
    v4l-utils \
    libglm-dev \
    zlib1g-dev \
    python3-tk \
    python3-numpy

ARG OPENCV_VERSION="4.7.0"
RUN echo holsasasasassa
COPY docker/build_opencv.sh build_opencv.sh 
RUN bash build_opencv.sh  ${OPENCV_VERSION} 
RUN apt update && apt install -y libzmq3-dev x11-apps
ENV AAA=BBB


RUN apt update -y && apt install -y software-properties-common

# # Deduplicator dependencies
# RUN add-apt-repository ppa:ubuntugis/ppa &&  \
#     apt update -y && \
#     apt-get install -y gdal-bin && \
#     echo 'GDAL VERSION:   ' && ogrinfo --version
#     # Version needs to be inserted into requirements txt
# RUN export CPLUS_INCLUDE_PATH=/usr/include/gdal && \ 
#     export C_INCLUDE_PATH=/usr/include/gdal
# RUN apt install -y libgdal-dev
# # RUN pip install GDAL==3.0.4 && 
# # RUN pip install fiona==1.8


# # RUN apt install -y libeigen3-dev python3-matplotlib python-dev libgdal-dev libcereal-dev libyaml-cpp-dev libpthread-stubs0-dev


# # # Deduplicator project
# # RUN git clone https://gitlab.bsc.es/ppc-bsc/software/deduplicator -b bsc && \
# #     cd deduplicator && \
# #     git submodule update --init --recursive && \
# # #    sed -i '64s/.*/    double error;    \/\/ in meter/' masa_protocol/include/objects.hpp && \
# # #    sed -i '69s/.*/    int idx;\n    int idy;\n/' masa_protocol/include/objects.hpp && \
# # #    sed -i '75s/.*/        archive( camera_id, latitude, longitude, object_id, error, speed, orientation, category, idx, idy );/' masa_protocol/include/objects.hpp && \
# #     mkdir build && \
# #     cd build && \
# #     cmake .. && \
# #     make -j8

# RUN echo hola
# RUN git clone https://pat:gc7sMZHxho-jyyFfcQRi@gitlab.bsc.es/ppc/benchmarks/smart-city/smart-city-compss.git -b newtracker
# WORKDIR /root/smart-city-compss
# # Compss obstacle detection dependencies
# # COPY requirements.txt requirements.txt


# # Then install your requirements
# RUN python3 -m pip install -r requirements.txt


# # Compss obstacle detection
# # Tracker class project
# # RUN git clone https://gitlab.bsc.es/ppc-bsc/software/tracker_CLASS.git -b dev && \
# #     cd tracker_CLASS && \
# #     cat src/modules.cpp && \ 
# #     git submodule update --init --recursive && \
# #     mkdir build  && \
# #     cd build && \
# #     cmake .. -DWITH_MATPLOTLIB=OFF && \
# #     make -j8

# # # Tracker class project
# # RUN git clone https://pat:zn1XXoMgB4896i533XPo@gitlab.bsc.es/ppc/benchmarks/smart-city/tracker.git -b dev && \
# #     cd tracker && \
# #     git submodule update --init --recursive && \
# #     mkdir build  && \
# #     cd build && \
# #     cmake .. -DWITH_MATPLOTLIB=OFF && \
# #     make -j8

# # RUN mkdir tracker
# # COPY tracker ./tracker

# # RUN ls && cp /root/tracker/build/track.cpython-36m-aarch64-linux-gnu.so smart-city-compss/lib/
# #RUN cp /root/deduplicator/build/deduplicator.cpython-36m-aarch64-linux-gnu.so smartcity-compss/lib
#     # cp /root/deduplicator/build/deduplicator.cpython-36m-x86_64-linux-gnu.so . && \


# # RUN mkdir -p /root/data/florencia/batoni/roi/
# # COPY roi/ /root/data/florencia/batoni/roi/
# RUN mkdir -p /root/b2drop 
# # Avoid warn message when waiting too much for getting path data from b2drop
# ENV PYDEVD_WARN_EVALUATION_TIMEOUT 30
# RUN apt install -y x11-apps
# # Establishing entrypoint for downloading the stubs and making the image ready at runtime
# # ENTRYPOINT ["./entrypoint.sh"]